const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'controllers', 'leaves.ts');
let content = fs.readFileSync(filePath, 'utf8');

// 1. Remove autoUpgradeUnpaidLeaves and its invocations
content = content.replace(/\/\*\*[\s\S]*?export const autoUpgradeUnpaidLeaves = async [\s\S]*?};\n/, '// Removed autoUpgradeUnpaidLeaves\n');
content = content.replace(/if\s*\(refundDays\s*>\s*0\)\s*\{\s*await autoUpgradeUnpaidLeaves\(leave\.employee_id\);\s*\}/g, '// autoUpgradeUnpaidLeaves removed');

// 2. Append applyLeaveOnBehalf if not present
if (!content.includes('applyLeaveOnBehalf')) {
  content += `\nexport const applyLeaveOnBehalf = async (req: any, res: any): Promise<void> => {\n    try {\n        const { employee_id, start_date, end_date, reason } = req.body;\n        const admin_id = String(req.user?.id);\n        const profile = await prisma.profiles.findUnique({ where: { id: employee_id } });\n        if (!profile) {\n            res.status(404).json({ error: "Employee not found." });\n            return;\n        }\n        const start = new Date(start_date);\n        const end = new Date(end_date);\n        const diffTime = end.getTime() - start.getTime();\n        const total_days = Math.ceil(diffTime / (1000 * 60 * 60 * 24)) + 1;\n        let daysToDeduct = Math.min(total_days, profile.available_leaves);\n        let newLeaveType = \`Compensatory Leave (\${daysToDeduct} Paid, \${total_days - daysToDeduct} Unpaid LOP)\`;\n        if (daysToDeduct >= total_days) newLeaveType = 'Compensatory Leave (Paid)';\n        if (daysToDeduct === 0) newLeaveType = 'Compensatory Leave (Unpaid - LOP)';\n        const durationText = total_days === 1 ? '1 day' : \`\${total_days} days\`;\n        const [newLeave] = await prisma.$transaction([\n            prisma.leave_requests.create({\n                data: {\n                    employee_id,\n                    leave_type: newLeaveType,\n                    start_date: start,\n                    end_date: end,\n                    total_days,\n                    paid_days: daysToDeduct,\n                    reason: \`[Applied on behalf by Admin] \${reason}\`,\n                    status: 'approved',\n                    approved_by: admin_id,\n                    approved_at: new Date(),\n                    admin_note: 'Automatically approved as it was applied by an admin on behalf of the employee.'\n                }\n            }),\n            prisma.profiles.update({ where: { id: employee_id }, data: { available_leaves: { decrement: daysToDeduct } } })\n        ]);\n        res.status(201).json({ message: 'Leave successfully applied and approved on behalf of the employee.', leave: newLeave });\n    } catch (error) {\n        res.status(500).json({ error: "Internal server error" });\n    }\n};\n`;
}

// 3. Append getMyCompOffs if not present
if (!content.includes('getMyCompOffs')) {
  content += `\nexport const getMyCompOffs = async (req: any, res: any): Promise<void> => {\n    try {\n        const employee_id = req.user?.id;\n        const compOffs = await prisma.compOffGrant.findMany({ where: { employeeId: String(employee_id) }, orderBy: { grantedAt: 'desc' } });\n        res.status(200).json(compOffs);\n    } catch (error) {\n        res.status(500).json({ error: "Failed to fetch comp-offs." });\n    }\n};\n`;
}

// 4. Append adjustUnpaidLeave if not present
if (!content.includes('adjustUnpaidLeave')) {
  content += `\nexport const adjustUnpaidLeave = async (req: any, res: any): Promise<void> => {\n    try {\n        const { leaveId } = req.body;\n        const employeeId = String(req.user?.id);\n        const leave = await prisma.leave_requests.findUnique({ where: { id: String(leaveId) } });\n        if (!leave || leave.employee_id !== employeeId) {\n            res.status(404).json({ error: "Leave not found." });\n            return;\n        }\n        if (leave.status !== 'pending' && leave.status !== 'approved') {\n            res.status(400).json({ error: "Cannot adjust a cancelled or rejected leave." });\n            return;\n        }\n        const currentPaid = leave.paid_days !== null ? leave.paid_days : leave.total_days;\n        const unpaidDays = leave.total_days - currentPaid;\n        if (unpaidDays <= 0) {\n            res.status(400).json({ error: "This leave is already fully paid." });\n            return;\n        }\n        const profile = await prisma.profiles.findUnique({ where: { id: employeeId } });\n        if (!profile || profile.available_leaves <= 0) {\n            res.status(400).json({ error: "No available leaves to adjust." });\n            return;\n        }\n        const now = new Date();\n        const leaveStart = new Date(leave.start_date);\n        if (leaveStart.getMonth() !== now.getMonth() || leaveStart.getFullYear() !== now.getFullYear()) {\n            res.status(400).json({ error: "Can only adjust leaves from the current calendar month." });\n            return;\n        }\n        const diffTime = now.getTime() - leaveStart.getTime();\n        const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24)); \n        if (diffDays > 8) { \n            res.status(400).json({ error: "Leave must be within the last 7 days to be adjustable." });\n            return;\n        }\n        const daysToUpgrade = Math.min(unpaidDays, profile.available_leaves);\n        const newPaidDays = currentPaid + daysToUpgrade;\n        let baseLeaveType = leave.leave_type.split(' (')[0];\n        let newLeaveTypeString = '';\n        if (newPaidDays >= leave.total_days) {\n            newLeaveTypeString = \`\${baseLeaveType} (Paid)\`;\n        } else {\n            newLeaveTypeString = newPaidDays > 0 ? \`\${baseLeaveType} (\${newPaidDays} Paid, \${leave.total_days - newPaidDays} Unpaid LOP)\` : \`\${baseLeaveType} (Unpaid - LOP)\`;\n        }\n        const [updatedLeave] = await prisma.$transaction([\n            prisma.leave_requests.update({ where: { id: leave.id }, data: { paid_days: newPaidDays, leave_type: newLeaveTypeString } }),\n            prisma.profiles.update({ where: { id: employeeId }, data: { available_leaves: { decrement: daysToUpgrade } } })\n        ]);\n        res.status(200).json({ message: "Leave successfully adjusted.", leave: updatedLeave });\n    } catch (error) {\n        res.status(500).json({ error: "Internal server error." });\n    }\n};\n`;
}

fs.writeFileSync(filePath, content, 'utf8');
console.log('Fixed leaves.ts successfully!');
